<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleEmailV2" Version="4.0.5.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.9" />
    <PackageReference Include="MimeKit" Version="4.13.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\FluentEmail.Core\FluentEmail.Core.csproj" />
  </ItemGroup>

</Project>
